version: '3'
services:
  backend:
    build: 
      context: ./django
    command: gunicorn imod_api.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build: 
      context: ./frontend
    volumes:
      -react_buld:/react/build
  
  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_buld:/var/www/react
    depends_on:
      - backend
      - frontend
volumes:
  react_buld: